/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthHangmanRouteImport } from './routes/_auth.hangman'
import { Route as AuthGalleryRouteImport } from './routes/_auth.gallery'
import { Route as AuthFeedRouteImport } from './routes/_auth.feed'
import { Route as AuthConnectionsRouteImport } from './routes/_auth.connections'
import { Route as AuthClassRouteImport } from './routes/_auth.class'
import { Route as AuthAudioRouteImport } from './routes/_auth.audio'
import { Route as ApiFeedUploadImageRouteImport } from './routes/api/feed.upload-image'
import { Route as ApiFeedUploadAudioRouteImport } from './routes/api/feed.upload-audio'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHangmanRoute = AuthHangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFeedRoute = AuthFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConnectionsRoute = AuthConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassRoute = AuthClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAudioRoute = AuthAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AuthRoute,
} as any)
const ApiFeedUploadImageRoute = ApiFeedUploadImageRouteImport.update({
  id: '/api/feed/upload-image',
  path: '/api/feed/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedUploadAudioRoute = ApiFeedUploadAudioRouteImport.update({
  id: '/api/feed/upload-audio',
  path: '/api/feed/upload-audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/audio': typeof AuthAudioRoute
  '/class': typeof AuthClassRoute
  '/connections': typeof AuthConnectionsRoute
  '/feed': typeof AuthFeedRoute
  '/gallery': typeof AuthGalleryRoute
  '/hangman': typeof AuthHangmanRoute
  '/api/feed/upload-audio': typeof ApiFeedUploadAudioRoute
  '/api/feed/upload-image': typeof ApiFeedUploadImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/audio': typeof AuthAudioRoute
  '/class': typeof AuthClassRoute
  '/connections': typeof AuthConnectionsRoute
  '/feed': typeof AuthFeedRoute
  '/gallery': typeof AuthGalleryRoute
  '/hangman': typeof AuthHangmanRoute
  '/api/feed/upload-audio': typeof ApiFeedUploadAudioRoute
  '/api/feed/upload-image': typeof ApiFeedUploadImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/audio': typeof AuthAudioRoute
  '/_auth/class': typeof AuthClassRoute
  '/_auth/connections': typeof AuthConnectionsRoute
  '/_auth/feed': typeof AuthFeedRoute
  '/_auth/gallery': typeof AuthGalleryRoute
  '/_auth/hangman': typeof AuthHangmanRoute
  '/api/feed/upload-audio': typeof ApiFeedUploadAudioRoute
  '/api/feed/upload-image': typeof ApiFeedUploadImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/audio'
    | '/class'
    | '/connections'
    | '/feed'
    | '/gallery'
    | '/hangman'
    | '/api/feed/upload-audio'
    | '/api/feed/upload-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/audio'
    | '/class'
    | '/connections'
    | '/feed'
    | '/gallery'
    | '/hangman'
    | '/api/feed/upload-audio'
    | '/api/feed/upload-image'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/onboarding'
    | '/_auth/audio'
    | '/_auth/class'
    | '/_auth/connections'
    | '/_auth/feed'
    | '/_auth/gallery'
    | '/_auth/hangman'
    | '/api/feed/upload-audio'
    | '/api/feed/upload-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiFeedUploadAudioRoute: typeof ApiFeedUploadAudioRoute
  ApiFeedUploadImageRoute: typeof ApiFeedUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/hangman': {
      id: '/_auth/hangman'
      path: '/hangman'
      fullPath: '/hangman'
      preLoaderRoute: typeof AuthHangmanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gallery': {
      id: '/_auth/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feed': {
      id: '/_auth/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthFeedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/connections': {
      id: '/_auth/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthConnectionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/class': {
      id: '/_auth/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof AuthClassRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audio': {
      id: '/_auth/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AuthAudioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/feed/upload-image': {
      id: '/api/feed/upload-image'
      path: '/api/feed/upload-image'
      fullPath: '/api/feed/upload-image'
      preLoaderRoute: typeof ApiFeedUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/upload-audio': {
      id: '/api/feed/upload-audio'
      path: '/api/feed/upload-audio'
      fullPath: '/api/feed/upload-audio'
      preLoaderRoute: typeof ApiFeedUploadAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAudioRoute: typeof AuthAudioRoute
  AuthClassRoute: typeof AuthClassRoute
  AuthConnectionsRoute: typeof AuthConnectionsRoute
  AuthFeedRoute: typeof AuthFeedRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  AuthHangmanRoute: typeof AuthHangmanRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAudioRoute: AuthAudioRoute,
  AuthClassRoute: AuthClassRoute,
  AuthConnectionsRoute: AuthConnectionsRoute,
  AuthFeedRoute: AuthFeedRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  AuthHangmanRoute: AuthHangmanRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiFeedUploadAudioRoute: ApiFeedUploadAudioRoute,
  ApiFeedUploadImageRoute: ApiFeedUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
